### PR TITLE
Project-1:- Embedding-Images-and-Video

### PR DESCRIPTION
**Pull request by hemantso**
##Project-1:- Embedding-Images-and-Video

Added main elements of Youtube page such as:-

   - The navbar including the Youtube icon, logo, search-bar, search-button, camera icon, notification icon, apps icon and user icon. 
 - The main section with a youtube video, subscribe button and notification bell icon, different icons and comments
- Suggested videos including auto-paly button
- footer

### CODE REVIEW

**Comment by arslanbisharat** [comment]
Added main element of Youtube page.
Main elements added such as:

--> The nav bar including Youtube icon , logo, search-bar, search-button, camera icon, notification icon, apps icon and user icon.
--> The main section with youtube video, subscribe button and notification bell icon, different icons and comments
—-> Suggested videos inculding auto-paly button
--> footer

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### You did great job so far :+1: 

Here are things you need to change, before this project can be approved:

### Navbar
* [ ] Navigation bar is no aligned like original one, search bar is a little lower  then others, button is not the same height as input field:
image
Original:
image

### Video
* [ ] This part should have like and dislike icons, right now you have images. Consider using Font Awesome for icons. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_like_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
* [ ] `Share` should be a button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
* [ ] Avatar of the user who uploaded the video should be present ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_avatar_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
* [ ] Next part is not aligned properly, take a look at screenshot from original website. Icons section is displayed directly above subscribe button.
image
Original:
image

### Sidebar Recommended videos
* [ ] This part should show the number of views, not some random text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/sidebar_views_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Consider the positioning of the icons and elements, please make this look like the original page (Icons: 'likes', 'share', 'save'.. has to be in one single line as the original page, not center)





- [ ] It’s better to delete commented code on your CSS file.  [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) you can see the information about this.
COMMENTLINE

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

[OPTIONAL]

- [ ] Consider adding the 'demo' link in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by hemantso** [comment]
- deleted single line comments in style.css
- corrected position of icons
screenshot

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### Good job you have done so far and making the review changes :clap: However, you have a few changes you need to make for your project to be approved.
- Remove the horizontal scroll
- Avoid using <br > tag in your html, use box model to achieve this
break

### Make these changes and resubmit for another review. Good luck.
- For assistance, contact me on @rOluochKe
- Happy coding!

**Comment by hemantso** [comment]
-removed <br> tag
- solved horizontal scrolling issue

**Review by MarioDena — APPROVED** [review]
## Hello team! my name is Mario.

Congratulations on making the requested changes.  :smiley: :smiley:

Your project does cover the requirements to be approved. Congratulations.

However I would recommend some optional changes.

## Optional Changes

- [ ] Work a little bit more on making your clone resemble the original. Font sizes, colors, horizontal lines, font styles. This project is a great opportunity to find out how real websites are styled.

- [ ] There are some repeated rules on your CSS, remember to keep your code DRY (Don't Repeat Yourself). This will be mandatory on future projects.

- [ ] Try using semantic HTML a bit more `section` `main` `aside` etc... This is a mandatory requirement but you can choose to do it or not this time.

- [ ] Update your project description to be more meaningful right now it only reads _"Microverse Repository"_


### All changes are optional this project is approved. :star::star:

## Code review by Mario Enrique Delgado Naranjo

**Pull request merged**
